# Generated by Django 4.0.3 on 2022-04-11 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_image2_alter_post_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 2, 25, 31, 612126)),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 2, 25, 31, 612152)),
        ),
    ]
