# Generated by Django 4.0.3 on 2022-04-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadpdf_remove_note_category_remove_note_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='resumes',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
