# Generated by Django 4.0.3 on 2022-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_uploadpdf_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
